name: youtube_app
description: YouTube video player and downloader app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  youtube_explode_dart: ^2.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  share_plus: ^7.2.1
  flutter_slidable: ^3.0.1
  url_launcher: ^6.2.2
  video_player: ^2.8.2
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#5D8AA8"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/
